language: cpp
compiler:
  - gcc
  - clang
env:
  - BUILD_CONFIGURATION=1
  - BUILD_CONFIGURATION=3
  - BUILD_CONFIGURATION=5
  - BUILD_CONFIGURATION=7
  - BUILD_CONFIGURATION=9
  - BUILD_CONFIGURATION=11
  - BUILD_CONFIGURATION=13
  - BUILD_CONFIGURATION=15
  - BUILD_CONFIGURATION=17
  - BUILD_CONFIGURATION=19
  - BUILD_CONFIGURATION=21
  - BUILD_CONFIGURATION=23
  - BUILD_CONFIGURATION=25
  - BUILD_CONFIGURATION=27
  - BUILD_CONFIGURATION=29
  - BUILD_CONFIGURATION=31

branches:
  only:
    - master

script: ctest -S ./CMake/usCTestScript_travis.cmake
